import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from "../../components/Navbar";

const Pricing: NextPage = () => {
  return (
    <>
      <Head>
        <title>Homework Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen ">
        <Navbar />
        <div className="flex flex-col items-center justify-center">
          <section className="flex w-full max-w-2xl flex-col items-center gap-12 pl-3 pt-12">
            <h2 className="text-6xl">Pricing</h2>
            <div className="flex w-full max-w-2xl items-center justify-center gap-1 pt-2">
              <div className="w-full rounded-[4px] border-2 border-black bg-lime-500">
                <h2 className="p-5 text-2xl">Free</h2>
                <p className="px-5">ask 10 questions per week!</p>
                <p className="p-5 text-3xl">
                  $0 <span className="text-xl">per month</span>
                </p>
                <button className=" m-5 border-2 border-black py-3 px-12">
                  Get Started
                </button>
                <p className="px-5 ">Inculudes:</p>
                <p className="px-5 pb-2">10 replies per week</p>
              </div>
              <div className="w-full">
                <div className="w-full rounded-[4px] border-2 border-black bg-fuchsia-400">
                  <h2 className="p-5 text-2xl">Pro</h2>
                  <p className="px-5">ask 200 questions per week!</p>
                  <p className="p-5 text-3xl">
                    $4.99 <span className="text-xl">per month</span>
                  </p>
                  <button className=" m-5 border-2 border-black py-3 px-12">
                    Purchase Subscription
                  </button>
                  <p className="px-5 ">Inculudes:</p>
                  <p className="px-5 pb-2">200 replies per week</p>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
};

export default Pricing;
