import { Container, Row, Spacer, Text } from '@nextui-org/react';
import { type NextPage } from 'next';
import Head from 'next/head';
import Ai from '../components/Ai';

const Home: NextPage = () => {
  //red, blue, green, yellow, and purple.
  return (
    <>
      <Head>
        <title>Homework AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spacer y={2} />
      <Container lg>
        <Row justify="center" align="center">
          <Text
            h1
            size={'$4xl'}
            css={{
              textGradient: '45deg, $blue600 -20%, $pink600 50%',
            }}
            weight="bold"
          >
            Ace Your Homework
          </Text>
        </Row>
        <Row justify="center" align="center">
          <Text
            hideIn={'sm'}
            size={'$3xl'}
            h2
            css={{
              textGradient: '45deg, $purple600 -20%, $pink600 100%',
            }}
          >
            Our advanced technology takes the stress out of homework!
          </Text>
        </Row>
        <Spacer y={2} />
        <Row justify="center" align="center" css={{ justifyContent: 'center' }}>
          <Ai />
        </Row>
      </Container>
    </>
  );
};

export default Home;
