import type { GetServerSideProps } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import BotInput from "../components/BotInput";
import Intro from "../components/Intro";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  //red, blue, green, yellow, and purple.
  return (
    <>
      <Head>
        <title>Homework Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen font-normal">
        <Navbar />
        <div className=""></div>
        <div className="flex flex-col items-center justify-center">
          <Intro />
          <section className="flex w-full max-w-2xl flex-col items-center gap-12 pl-3 pt-12">
            <BotInput />
          </section>
          <section className="flex w-full max-w-2xl flex-col items-center justify-center gap-1 pt-12">
            <h2 className="text-2xl">Call to Action</h2>
            <div className="flex w-full max-w-2xl items-center justify-center gap-1 pt-2">
              <a
                className="rounded-[4px] border-2 border-black px-4 py-2"
                href="#"
              >
                Try For Free
              </a>
              <a
                className="rounded-[4px] border-2 border-black px-4 py-2"
                href="#"
              >
                Purchese Subscription
              </a>
            </div>
          </section>
        </div>
      </main>
    </>
  );
};

export default Home;

// getserversideprops
export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};
