name: Daily Cron

on:
  schedule:
    - cron: '0 0 * * *' # runs once a day at 00:00 UTC
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Make HTTP POST request
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"key":"value"}' https://albertsolver.com/api/counter-reset
